# Generated by Django 5.1.1 on 2024-10-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_equipment_userprofile_eqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='modelname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
