# Generated by Django 5.1.1 on 2024-10-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_equipment_availability_equipment_modelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='equipment',
            name='eqtype',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
