# Generated by Django 5.1.1 on 2024-10-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_equipment_brand_equipment_eqtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='eqtype',
            new_name='kind',
        ),
    ]
